project:
  type: website
  output-dir: docs

website:
  title: "David R. M. Graf"
  description: "Academic Website David R. M. Graf"
  navbar:
    background: gray-900
    search: false
    left:   # You can comment out all navigation items here if you just like to keep the index page only
      - text: Home
        href: index.qmd
      - text: Research
        href: publications.qmd
      - text: CV
        href: files/CV.pdf
  page-footer:
    background: "#F6F5F3"
    center: Â© 2026  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
    right:
      - icon: github
        href: https://github.com/davidrmgraf
        target: _blank
          
format:
  html:
    theme: journal
    css: styles.css
    toc: false
    linkcolor: darkblue
    email-obfuscation: javascript
    fig-align: center
    link-external-icon: false